# https://github.com/hico-horiuchi/ansible-playbooks/blob/master/apt/apt.yml
- name: apt-get update & upgrade
  apt:
      update_cache=yes
      upgrade=dist
  register: task_result

- name: apt-get autoremove
  apt:
      autoremove: yes

- name: apt-get clean
  apt:
      autoclean: yes

# reboot & wait
#
# https://www.jeffgeerling.com/blog/2018/reboot-and-wait-reboot-complete-ansible-playbook
- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
      when: task_result is changed

- ping:

