# repo url var
satellite_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66396537303335653635366230313062353231613132333936383837643535376534643261353037
          6161366264363139386264633036333963313933653763300a383238336138366530386362343435
          65343530326161343761386339386366393266303732363438306633396363383531666263323731
          3638303331666431620a333465666561353866303438393261613238353632373032653463316162
          34306163663964333864323134396363303731643333383138656337393266623062306535636631
          32313564386138336138636231373636343565303463353334313035356264313132323662643965
          31376264663939306461383837396531666366343034656336323061626361373132646339353130
          61646531633635663932

# Note: the 'name' value should match the github repo's name (including case)
# Note #2: if the repo is a tool included in kali, make sure to remove the kali
# version first
git_repos:
    - name: SecLists
      url: https://github.com/danielmiessler/SecLists
      branch: master
      shell: "ln -s /opt/SecLists /"
    - name: wfuzz
      url: https://github.com/xmendez/wfuzz/
      branch: dev
      # purge in case the package is already there - we want the most up to date
      #shell: "apt purge wfuzz -y; cd /opt/wfuzz && pip install -r requirements.txt && python setup.py install"
      shell: "apt purge wfuzz -y; ls /opt/wfuzz"
    - name: sqlmap
      url: https://github.com/sqlmapproject/sqlmap
      branch: master
      shell: "apt purge sqlmap -y; ln -s /opt/sqlmap/sqlmap.py /usr/bin/sqlmap"
    - name: Sublist3r
      url: https://github.com/aboul3la/Sublist3r
      branch: master
      shell: "cd /opt/Sublist3r && pip install -r requirements.txt && python setup.py install"
    - name: satellite
      url: "{{ satellite_url }}"
      branch: master
      shell: "ls /opt/satellite"
    - name: tplmap
      url: https://github.com/epinna/tplmap
      branch: master
      shell: "cd /opt/tplmap && pip install -r requirements.txt"
    - name: CrackMapExec
      url: https://github.com/byt3bl33d3r/CrackMapExec
      recursive: yes
      branch: master
      shell: "ls"
      # TODO fix this bullshit
      #shell: "echo \"pip install -U pipenv\npipenv install\npipenv shell\npython setup.py install\" > /opt/CrackMapExec/prohib_install.txt"
    - name: impacket
      url: https://github.com/SecureAuthCorp/impacket
      recursive: yes
      branch: master
      shell: "ls"
    - name: commix
      url: https://github.com/commixproject/commix
      branch: master
      shell: "ls /opt/commix"
    - name: parameth
      url: https://github.com/maK-/parameth
      branch: master
      shell: "cd /opt/parameth && pip install -r requirements.txt"
    - name: api_wordlist
      url: https://github.com/chrislockard/api_wordlist
      branch: master
      shell: "ls /opt/api_wordlist"
    - name: fuzz.txt
      url: https://github.com/Bo0oM/fuzz.txt
      branch: master
      shell: "ls /opt/fuzz.txt/"
    - name: dirsearch
      url: https://github.com/nikallass/dirsearch
      branch: master
      shell: "ls /opt/dirsearch/"
    - name: node-dirbuster
      url: https://github.com/daviddias/node-dirbuster
      branch: master
      shell: "mkdir /usr/share/dirbuster && ln -s /opt/node-dirbuster/lists /usr/share/dirbuster/wordlists"
      warn: False
    - name: fuzzmost
      url: https://github.com/thelikes/fuzzmost
      branch: master
      shell: "ln -s /opt/fuzzmost/ /"
    - name: wzrd
      url: https://github.com/thelikes/wzrd
      branch: master
      shell: "ln -s /opt/wzrd/web/wzrd-gobuster.sh /usr/bin/"
    - name: dnsgen
      url: https://github.com/projectante/dnsgen
      branch: master
      shell: "cd /opt/dnsgen && pip3 install -r requirements.txt && python3 setup.py install"
    - name: ShoScan
      url: https://github.com/pathetiq/ShoScan
      branch: master
      shell: "cd /opt/ShoScan && pip install -r requirements.txt"
    - name: fav-up
      url: https://github.com/pielco11/fav-up
      branch: master
      shell: "cd /opt/fav-up && pip3 install -r requirements.txt"
    - name: massdns
      url: https://github.com/blechschmidt/massdns
      branch: master
      shell: "cd /opt/massdns && make"
    - name: LinkFinder
      url: https://github.com/GerbenJavado/LinkFinder
      branch: master
      shell: "cd /opt/LinkFinder && pip3 install -r requirements.txt && python setup.py install"
    - name: cc.py
      url: https://github.com/si9int/cc.py
      branch: master
      shell: "ls /opt/cc.py"
    - name: Arjun
      url: https://github.com/s0md3v/Arjun
      branch: master
      shell: "ls /opt/Arjun"
    - name: pathbrute
      url: https://github.com/milo2012/pathbrute
      branch: master
      shell: "ls /opt/pathbrute"
    - name: xxeserv
      url: https://github.com/staaldraad/xxeserv
      branch: master
      shell: "ls /opt"
    - name: evilarc
      url: https://github.com/ptoomey3/evilarc
      branch: master
      shell: "ls /opt"
    - name: fuxploider
      url: https://github.com/almandin/fuxploider
      branch: master
      shell: "ls /opt"
    - name: SIET
      url: https://github.com/Sab0tag3d/SIET
      branch: master
      shell: "ls /opt"
    - name: NoSQLMap
      url: https://github.com/codingo/NoSQLMap
      branch: master
      shell: "ls /opt"
    - name: LFISuite
      url: https://github.com/D35m0nd142/LFISuite
      branch: master
      shell: "ls /opt"
    - name: requestify
      url: https://github.com/ggabarrin/requestify
      branch: master
      shell: "ls /opt"
    - name: LinEnum
      url: https://github.com/rebootuser/LinEnum
      branch: master
      shell: "ls /opt"
    - name: linux-local-enumeration-script
      url: https://github.com/Arr0way/linux-local-enumeration-script
      branch: master
      shell: "ls /opt"
    - name: Linux_Exploit_Suggester
      url: https://github.com/InteliSecureLabs/Linux_Exploit_Suggester
      branch: master
      shell: "ls /opt"
    - name: Hwacha
      url: https://github.com/n00py/Hwacha
      branch: master
      shell: "ls /opt"
    - name: nuclei-templates
      url: https://github.com/projectdiscovery/nuclei-templates
      branch: master
      shell: "ls /opt"
    - name: github-search
      url: https://github.com/gwen001/github-search
      branch: master
      shell: "cd /opt/github-search && pip3 install -r requirements3.txt"
    - name: Spray
      url: https://github.com/Greenwolf/Spray
      branch: master
      shell: "ls /opt"
    - name: Pwdb-Public
      url: https://github.com/FlameOfIgnis/Pwdb-Public
      branch: master
      shell: "ls /opt"
    - name: ldapdomaindump
      url: https://github.com/dirkjanm/ldapdomaindump
      branch: master
      shell: "ls /opt"
    - name: fuzzdb
      url: https://github.com/fuzzdb-project/fuzzdb
      branch: master
      shell: "ls /opt"
    - name: tennc-fuzzdb
      url: https://github.com/tennc/fuzzdb
      branch: master
      shell: "ls /opt"
    - name: dnsvalidator
      url: https://github.com/vortexau/dnsvalidator
      branch: master
      shell: "cd /opt/dnsvalidator && python3 setup.py install"
    - name: brutespray
      url: https://github.com/x90skysn3k/brutespray
      branch: master
      shell: "cd /opt/brutespray && pip3 install -r requirements.txt"
    - name: BruteX
      url: https://github.com/1N3/BruteX
      branch: master
      shell: "ls /opt/BruteX"
    - name: Kadimus
      url: https://github.com/P0cL4bs/Kadimus
      branch: master
      shell: "ls /opt/Kadimus"
    - name: exploitdb
      url: https://github.com/offensive-security/exploitdb.git
      branch: master
      shell: "ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit && cp -n /opt/exploitdb/.searchsploit_rc ~/"
    - name: IIS-ShortName-Scanner
      url: https://github.com/irsdl/IIS-ShortName-Scanner
      branch: master
      shell: "ls /opt/IIS-ShortName-Scanner"
    - name: Python-dsstore
      url: https://github.com/gehaxelt/Python-dsstore
      branch: master
      shell: "ls /opt/Python-dsstore"
    - name: dvcs-ripper
      url: https://github.com/kost/dvcs-ripper
      branch: master
      shell: "ls /opt/dvcs-ripper"
